### ISSUE TITLE
Prism 的 IDialogWindow 应该怎么写？

### ISSUE THREAD

**Issue by shinywong** [shinywong/DummyRepo#1]
@LGTCO

抱歉只能以这种方式联系到你，如有打扰请谅解。

你在 [这里](https://github.com/PrismLibrary/Prism/pull/1682#issuecomment-483201594) 发布的评论里的这个图片：

![1](https://user-images.githubusercontent.com/10369132/88570152-2b521100-d06e-11ea-9c0a-886ddcec8bbc.png)

我也是这么写的，我感觉 Prism 的帮助里也是这样的，我是报另外一个错误：

`DryIoc.ContainerException: 'Implementation type is not specified when using automatic constructor selection:...`

noufionline 的下面这个评论我没搞明白到底什么意思：

`Why you are passing the DialogWindow name as uri. DialogWindow is just the container in which your view will be injected. You must be passing the view which you want to inject inside the DialogWindow.`

这个究竟应该怎么写才行呢？网上基本搜不到。非常感谢！

**Comment by LGTCO** [comment]
你好, 我没遇到过这个错误。不过，关于DialogWindow的使用

需要一个类，注册为DialogWindow,这个类相当于一个容器，设计的弹出内容控件，将被包含在该类中显示
![devenv_H74rsr2v76](https://user-images.githubusercontent.com/23730062/88666031-18911800-d112-11ea-9c9c-b57325e441a2.png)
![devenv_4FDBi5PCsy](https://user-images.githubusercontent.com/23730062/88666057-2050bc80-d112-11ea-97d3-dcb8bb52e963.png)

这个为弹出页面的内容控件，注册并命名
![image](https://user-images.githubusercontent.com/23730062/88666254-6574ee80-d112-11ea-9c1d-2bd2680329b9.png)
![devenv_2ApOnfjS3u](https://user-images.githubusercontent.com/23730062/88666263-69087580-d112-11ea-937e-f603fef2ec3a.png)

调用该弹出页就用：
_dialogService.ShowDialog("TipView",null,null);

不好意思这时候才给回复

**Comment by LGTCO** [comment]
```C#
protected override void RegisterTypes(IContainerRegistry containerRegistry){
            containerRegistry.RegisterDialogWindow<DialogContainer>();
            containerRegistry.RegisterDialog<TipView>("TipView");   
}

public partial class DialogContainer : Window, IDialogWindow
{
        public DialogContainer()
        {
            InitializeComponent();
        }

        public IDialogResult Result { get; set; } 
 }

    public partial class TipView : UserControl
    {
        public TipView()
        {
            InitializeComponent();
        }
    }
```
/// DialogContainer Xaml
```C#
<Window x:Class="IQVu.Wpf.DialogContainer"
        xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
        xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
        xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
        xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
        mc:Ignorable="d"
        Height="300" 
        Width="500"
        WindowStartupLocation="CenterOwner"
        Title="DialogWindowContainer" >
    <Grid>
        <ContentControl></ContentControl>
    </Grid>
</Window>
```
我知道自己不大能描述清楚，有什么问题咱们可以再交流。

**Comment by LGTCO** [comment]
你好，你能给出出现该错误时的实例 代码吗？

**Comment by shinywong** [comment]
@LGTCO 

谢谢详细的回复。

现在搞明白了，IDialogWindow 只是个容器，必须要将继承 IDialogAware 的 UserControl 放入到 IDialogWindow 中。
我还以为界面的东西全部放到 IDialogWindow 里，然后 ShowDialog IDialogWindow。
Prism 的帮助写的不太清楚。

现在已经参照你的代码，把我的工程改好，现在可以跑通了。
非常感谢！
